#!/bin/bash

BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'
NC='\033[0m' # no color

current_shell=$(ps -p $(ps -p $$ -o ppid=) -o comm=)

# Get the history for new possible alias

useBashHistory(){
	declare -A counter

	# Extract last 2000 commands and save only the first word (the principal command)
	commands=$(tail -n 2000 ~/.bash_history | awk '{print $1}')

	# Command counter
	for command in $commands; do
	    ((counter[$command]++))
	done

	# Sort and show commands by quantity
	echo -e "\n🔁 ${MAGENTA}Most frequent commands (last 2000 Bash history entries):\n${NC}"

	for command in "${!counter[@]}"; do
		number=${counter[$command]}

		if [[ number -gt 5 ]]
		then
	    		echo -e "${MAGENTA}$command: $number ${NC}" >> most_words.txt
	    	fi
	done

	sort -h -t' ' -k2 most_words.txt | tail -n50
	rm -f most_words.txt
}


useZshHistory(){
	declare -A counter

	# Extact last used commands from ~/.zsh_history and save only the first word
	commands=$(sed 's/^: [0-9]*:[0-9]*;//' ~/.zsh_history | awk -F' ' '{print $1}' | grep -v '^[[:space:]]*$' | grep -v '^[[:punct:]]*$')

	# Command counter
	for command in $commands; do
	    ((counter[$command]++))
	done

	# Sort and show commands by quantity
	echo -e "\n🔁 ${ORANGE}Most used commands in zsh_history:\n${NC}"

	for command in "${!counter[@]}"; do
		number=${counter[$command]}

		if [[ number -gt 5 ]]
		then
	    		echo -e "${ORANGE}$command: $number${NC}" >> most_words.txt
	    	fi
	done

	sort -h -t' ' -k2 most_words.txt | tail -n50
	rm -f most_words.txt
}

autoDetect(){
	current_shell=$(ps -p $(ps -p $$ -o ppid=) -o comm=)

	if [[ "$current_shell" == "zsh" ]];
	then
		echo -e "${WHITE}Using $current_shell history file...${NC}"
		useZshHistory
	elif [[ "$current_shell" == "bash" ]]; 
	then
		echo -e "${WHITE}Using $current_shell history file...${NC}"
		useBashHistory
	else
		echo -e "${WHITE}Unknown shell. Try using the manual mode${NC}."
	fi
}


# Get option history
echo -e "${BLUE}Welcome ${GREEN}$USER${BLUE} to the Smart Alias program.
Choose how you want to load your command history${NC}:	"

echo -e "
${BLUE}1${NC}. ${WHITE}Automatic (auto-detect your shell)${NC}
${BLUE}2${NC}. ${WHITE}From ~/.bash_history${NC}
${BLUE}3${NC}. ${WHITE}From ~/.zsh_history (Zsh users only)${NC}

${BLUE}'q'${NC} or ${BLUE}'Q'${NC} to ${BLUE}Quit${NC}
"

echo -ne "${WHITE}Enter option${NC} : "
read option

case $option in
	1)
	 sleep 1s
	 autoDetect
	;;
	2)
	 sleep 1s
	 useBashHistory
	;;
	3)
	 sleep 1s
	 useZshHistory
	;;
	"q" | "Q")
	 echo -e "${WHITE}Exiting...${NC}"
	 sleep 1s
	 exit 0
	;;
	*)
	 echo -e "${RED}Error, option not recognized${NC}"
	 exit 0
	;;
esac
