#!/bin/bash

black='\033[0;30m'
red='\033[0;31m'
green='\033[0;32m'
orange='\033[0;33m'
blue='\033[0;34m'
magenta='\033[0;35m'
light_magenta='\033[0;95m'
cyan='\033[0;36m'
white='\033[0;37m'
nc='\033[0m' # no color

normal='\033[0m' # normal
bold='\033[1m'
dim='\033[2m'
italic='\033[3m'
underline='\033[4m'
bold_italic="${bold}${italic}"

bold_green='\033[1;32m'
bold_blue='\033[1;34m'
italic_blue='\033[3;34m'
under_blue='\033[4;34m'


current_shell=$(ps -p $(ps -p $$ -o ppid=) -o comm=)

# Get the history for new possible alias

useBashHistory(){
	declare -A counter

	# Extract last 2000 commands and save only the first word (the principal command)
	commands=$(tail -n 2000 ~/.bash_history | awk '{print $1}')

	# Command counter
	for command in $commands; do
	    ((counter[$command]++))
	done

	# Sort and show commands by quantity
	echo -e "\n🔁 ${magenta}Most frequent commands (last 2000 Bash history entries):\n${nc}"

	for command in "${!counter[@]}"; do
		number=${counter[$command]}

		if [[ number -gt 5 ]]
		then
	    		echo -e "${magenta}$command: $number ${nc}" >> most_words.txt
	    	fi
	done

	sort -h -t' ' -k2 most_words.txt | tail -n50
	rm -f most_words.txt
}


useZshHistory(){
	declare -A counter

	# Extact last used commands from ~/.zsh_history and save only the first word
	commands=$(sed 's/^: [0-9]*:[0-9]*;//' ~/.zsh_history | awk -F' ' '{print $1}' | grep -v '^[[:space:]]*$' | grep -v '^[[:punct:]]*$')

	# Command counter
	for command in $commands; do
	    ((counter[$command]++))
	done

	# Sort and show commands by quantity
	echo -e "\n🔁 ${orange}Most used commands in zsh_history:\n${nc}"

	for command in "${!counter[@]}"; do
		number=${counter[$command]}

		if [[ number -gt 5 ]]
		then
	    		echo -e "${orange}$command: $number${nc}" >> most_words.txt
	    	fi
	done

	sort -h -t' ' -k2 most_words.txt | tail -n50
	rm -f most_words.txt
}

autoDetect(){
	current_shell=$(ps -p $(ps -p $$ -o ppid=) -o comm=)

	if [[ "$current_shell" == "zsh" ]];
	then
		echo -e "${white}Using $current_shell history file...${nc}"
		useZshHistory
	elif [[ "$current_shell" == "bash" ]];
	then
		echo -e "${white}Using $current_shell history file...${nc}"
		useBashHistory
	else
		echo -e "${white}Unknown shell. Try using the manual mode${nc}."
	fi
}


# Get option history
echo -e "${green}Welcome ${bold_blue}${USER}${green} to the Smart Alias script${white}.
${white}Choose how you want to load your command history: ${nc}"

echo -e "
${italic_blue}1${white}. ${under_blue}Automatic ${white}(auto-detect your shell)${nc}
${italic_blue}2${white}. ${white}From ${under_blue}~/.bash_history${nc}
${italic_blue}3${white}. ${white}From ${under_blue}~/.zsh_history${white} (Zsh users only)${nc}

${blue}'${italic_blue}q${BLUE}'${white} or ${blue}'${italic_blue}Q${BLUE}'${white} to ${under_blue}Quit${nc}
"

echo -ne "${white}Enter option : ${light_magenta}"
read option
echo -e "${white}"

case $option in
	1)
	 sleep 1s
	 autoDetect
	;;
	2)
	 sleep 1s
	 useBashHistory
	;;
	3)
	 sleep 1s
	 useZshHistory
	;;
	"q" | "Q")
	 echo -e "${white}Exiting...${nc}"
	 sleep 1s
	 exit 0
	;;
	*)
	 echo -e "${red}Error, option not recognized${nc}"
	 exit 0
	;;
esac
