#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'
NC='\033[0m' # no color


current_shell=$(ps -p $(ps -p $$ -o ppid=) -o comm=)


showBashHistory(){
	grep -o -i '\<git\>' ~/.bash_history | wc -l
}

showZshHistory(){
	sed 's/^: [0-9]*:[0-9]*;//' ~/.zsh_history | grep -o -i '\<git\>' | wc -l
}


showAutomatic(){

	current_shell=$(ps -p $(ps -p $$ -o ppid=) -o comm=)

	if [[ "$current_shell" == "zsh" ]];
	then
		echo -e "Using $current_shell history file..."
		showZshHistory
	elif [[ "$current_shell" == "bash" ]]; 
	then
		echo -e "Using $current_shell history file..."
		showBashHistory
	else
		echo -e "Unknown shell. Try using the manual mode "
	fi

}



echo -e "$USER ¿From where the script gonna get the history of your commands?"

echo -e "
1. Automatic
2. From ~/.bash_history
3. From ~/.zsh_history (only for zsh users)
"

echo -n "Enter option (number): "
read fromWhere


case $fromWhere in
	1)
	 showAutomatic
	 exit 0
	;;
	2)
	 showBashHistory
	 exit 0
	;;
	3)
	 showZshHistory
	 exit 0
	;;
esac
